server:
<<<<<<< HEAD
  port: 8083
=======
  port: 8082
>>>>>>> 93490155c4b9b8723a72cb498c7327f2b6ce7f07

spring:
  application:
    name: client1

eureka:
  client:
    securePortEnabled: true
    ssl:
      key-store: client.p12
      key-store-password: client
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/