spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ohmygod0512/spring-cloud-config.git
          #username:
          #password:
          search-paths: SC-BOOK-CONFIG
  application:
    name: ch11-2-config-server
server:
    port: 9090