zuul:
  routes:
    # 将所有/client开头的url映射到client-a服务中去
    zuul-gateway:
      path: /client/**
      serviceId: client-a
  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000
hystrix:
  command:
    default:
      execution:
        timeout: 
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 350000
  ReadTimeout: 350000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  okhttp:
    enabled: true